### ISSUE TITLE
Do we need Side() in players.py?

### ISSUE THREAD

**Issue by cclauss** [671620616/PhantomChess#57]
I find the concepts of `Side()` and `color.color`to be confusing and of limited value.  Each player and each piece should know their own color (e.g. should have a color attribute that is set to either `white` or `black`).  Player and Piece should also have a method called `.opponent()`.  Your thoughts on the pros/cons of getting rid of `Side()`?

**Comment by 671620616** [comment]
Probably not - I think it's similar to the `Namespace` class (from issue #12 ).  Originally I added it with flexability in mind, but now I don't think it serves any other purpose than having to type `.color.color` rather than simply `.color`.  As I plan to do with Namespace, I'll start to phase this out.

**Comment by 671620616** [comment]
In fact, as of commit 3b8c8f68a4d342676af633311b56293326bc2349, it has been completely removed.
